#!/usr/bin/python3

import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)

sensor_pin = 17
led_pin = 19

GPIO.setup(sensor_pin, GPIO.IN)
GPIO.setup(led_pin, GPIO.OUT)

try:
    while True:
        print(GPIO.input(sensor_pin))
        GPIO.output(led_pin, GPIO.input(sensor_pin))
        time.sleep(1)
except KeyboardInterrupt:  
    # here you put any code you want to run before the program   
    # exits when you press CTRL+C  
    print("\n") # print value of counter  
  
except:  
    # this catches ALL other exceptions including errors.  
    # You won't get any error messages for debugging  
    # so only use it once your code is working  
    print ("Other error or exception occurred!")  
  
finally:  
    GPIO.cleanup() # this ensures a clean exit  
